import React, { useState } from 'react';
import { ChartConfig, Dataset } from '../types';
import { ChartRenderer } from './ChartRenderer';

interface ReportBuilderProps {
  charts: ChartConfig[];
  dataset: Dataset;
}

export const ReportBuilder: React.FC<ReportBuilderProps> = ({ charts, dataset }) => {
  // Simplified report builder: list all charts, toggle visibility, add comments
  const [selectedCharts, setSelectedCharts] = useState<string[]>(charts.map(c => c.id));
  const [notes, setNotes] = useState<Record<string, string>>({});

  const toggleChart = (id: string) => {
    if (selectedCharts.includes(id)) {
      setSelectedCharts(selectedCharts.filter(c => c !== id));
    } else {
      setSelectedCharts([...selectedCharts, id]);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex flex-col lg:flex-row gap-6 h-full">
      {/* Sidebar Controls */}
      <div className="w-full lg:w-80 bg-white border border-slate-200 rounded-xl p-4 flex flex-col gap-4 h-fit">
         <h2 className="font-bold text-slate-900">Report Contents</h2>
         <p className="text-xs text-slate-500">Select elements to include in your PDF report.</p>
         
         <div className="space-y-2 max-h-[400px] overflow-y-auto">
            {charts.map(chart => (
               <label key={chart.id} className="flex items-center gap-3 p-2 hover:bg-slate-50 rounded cursor-pointer border border-transparent hover:border-slate-100">
                  <input 
                    type="checkbox" 
                    checked={selectedCharts.includes(chart.id)}
                    onChange={() => toggleChart(chart.id)}
                    className="w-4 h-4 text-indigo-600 rounded focus:ring-indigo-500"
                  />
                  <span className="text-sm text-slate-700 truncate">{chart.title}</span>
               </label>
            ))}
         </div>
         
         <button onClick={handlePrint} className="mt-auto bg-slate-900 text-white py-2 rounded-lg font-medium hover:bg-slate-800 transition-colors flex items-center justify-center gap-2">
           <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
           </svg>
           Print / Save PDF
         </button>
      </div>

      {/* Document Preview */}
      <div className="flex-1 bg-slate-100 overflow-y-auto p-4 lg:p-8 rounded-xl">
         <div className="bg-white shadow-lg min-h-[1123px] w-full max-w-[794px] mx-auto p-12 flex flex-col gap-12 print:shadow-none print:w-full print:max-w-none print:p-0">
            {/* Report Header */}
            <div className="border-b-2 border-slate-900 pb-6 mb-4">
               <h1 className="text-4xl font-bold text-slate-900 mb-2">Data Analysis Report</h1>
               <div className="flex justify-between text-slate-500 text-sm">
                  <span>Dataset: {dataset.name}</span>
                  <span>{new Date().toLocaleDateString()}</span>
               </div>
            </div>

            {charts.filter(c => selectedCharts.includes(c.id)).map((chart, idx) => (
               <div key={chart.id} className="break-inside-avoid">
                  <h3 className="text-xl font-bold text-slate-800 mb-2">{idx + 1}. {chart.title}</h3>
                  <div className="h-64 w-full bg-slate-50 border border-slate-100 rounded-lg mb-4 p-4 print:bg-white print:border-none">
                     <ChartRenderer config={chart} data={dataset.data} showGrid={false} showLegend={true} />
                  </div>
                  <textarea 
                     className="w-full text-sm text-slate-600 bg-transparent border-none focus:ring-0 p-0 resize-none italic"
                     placeholder="Add your analysis notes here..."
                     rows={3}
                     value={notes[chart.id] || ''}
                     onChange={(e) => setNotes({...notes, [chart.id]: e.target.value})}
                  />
               </div>
            ))}
            
            <div className="mt-auto pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
               Generated by AutoViz-Insight
            </div>
         </div>
      </div>
    </div>
  );
};
